### ISSUE TITLE
out of bounds

### ISSUE THREAD

**Issue by yangzhaojason** [MingboHong/SSPNet-Scale-Selection-Pyramid-Network-for-Tiny-Person-Detection-from-UAV-Images#1]
mmdet/models/module/heatmap.py line81
threshold = -bg_score_sorted[bg_num - 1]

**Comment by MingboHong** [comment]
> mmdet/models/module/heatmap.py line81 threshold = -bg_score_sorted[bg_num - 1]

Can you provide more information about this bug? Or, we have released the detailed code， and you can check it in this repo
