### ISSUE TITLE
How to inference?

### ISSUE THREAD

**Issue by guofeng1996** [MingboHong/SSPNet-Scale-Selection-Pyramid-Network-for-Tiny-Person-Detection-from-UAV-Images#10]
My inference command is :python demo/image_demo.py 2.jpg     configs/sspnet/faster_rcnn_r50_sspnet_1x_coco_new.py     checkpoints/epoch_10.pth     --device cuda:3

Traceback (most recent call last):
  File "demo/image_demo.py", line 50, in <module>
    main(args)
  File "demo/image_demo.py", line 30, in main
    result = inference_detector(model, args.img)
  File "/home/SSPNet-master/mmdet/apis/inference.py", line 129, in inference_detector
    data = test_pipeline(data)
  File "/home/SSPNet-master/mmdet/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/home/SSPNet-master/mmdet/datasets/pipelines/loading.py", line 61, in __call__
    corner = results['img_info']['corner']
KeyError: 'corner

How can I fix it? or How to inference a image?

**Comment by MingboHong** [comment]
You need to modify the “test_pipeline” in “coco_detection.py”

test_pipeline = [
dict(type='LoadSubImageFromFile')    ===>  dict(type='LoadImageFromFile')
xxxxx
xxxxx
xx
]

where "dict(type='LoadImageFromFile')"  avoids the use of patch images for inference.

**Comment by guofeng1996** [comment]
Thank you very much. I did it!

**Comment by guyuehuqaq** [comment]
> You need to modify the “test_pipeline” in “coco_detection.py”
> 
> test_pipeline = [ dict(type='LoadSubImageFromFile') ===> dict(type='LoadImageFromFile') xxxxx xxxxx xx ]
> 
> where "dict(type='LoadImageFromFile')" avoids the use of patch images for inference.

Is your reasoning page like this? I use your open source code, the accuracy is always a few points lower, can you tell me what's going on?please
