### ISSUE TITLE
Which dataset is it?

### ISSUE THREAD

**Issue by guyuehuqaq** [MingboHong/SSPNet-Scale-Selection-Pyramid-Network-for-Tiny-Person-Detection-from-UAV-Images#19]
Hello, I use the erase_with_uncertain_dataset dataset in Tiny Person and the test results in your paper are different, which part of the dataset are you using?

**Comment by MingboHong** [comment]
> Hello, I use the erase_with_uncertain_dataset dataset in Tiny Person and the test results in your paper are different, which part of the dataset are you using?

emm， i guess you need to cut the image into small patchs， sent image patchs  into network for training rather than whole images

**Comment by guyuehuqaq** [comment]
> 

I followed your configuration file. I used the label file you gave, all the data sets of train and test to train, and the average accuracy is 2-3 points lower than the one given in your article. Is this normal?

**Comment by guyuehuqaq** [comment]
> > Hello, I use the erase_with_uncertain_dataset dataset in Tiny Person and the test results in your paper are different, which part of the dataset are you using?
> 
> emm， i guess you need to cut the image into small patchs， sent image patchs into network for training rather than whole images

I followed your configuration file. I used the label file you gave, all the data sets of train and test to train, and the average accuracy is 2-3 points lower than the one given in your article. Is this normal?

**Comment by MingboHong** [comment]
> > > Hello, I use the erase_with_uncertain_dataset dataset in Tiny Person and the test results in your paper are different, which part of the dataset are you using?
> > 
> > 
> > emm， i guess you need to cut the image into small patchs， sent image patchs into network for training rather than whole images
> 
> I followed your configuration file. I used the label file you gave, all the data sets of train and test to train, and the average accuracy is 2-3 points lower than the one given in your article. Is this normal?
It's weird.

**Comment by guyuehuqaq** [comment]
> > > > Hello, I use the erase_with_uncertain_dataset dataset in Tiny Person and the test results in your paper are different, which part of the dataset are you using?
> > > 
> > > 
> > > emm， i guess you need to cut the image into small patchs， sent image patchs into network for training rather than whole images
> > 
> > 
> > I followed your configuration file. I used the label file you gave, all the data sets of train and test to train, and the average accuracy is 2-3 points lower than the one given in your article. Is this normal?
> > It's weird.

Do you divide the image into patches during training and testing?

**Comment by guyuehuqaq** [comment]
> > > > Hello, I use the erase_with_uncertain_dataset dataset in Tiny Person and the test results in your paper are different, which part of the dataset are you using?
> > > 
> > > 
> > > emm， i guess you need to cut the image into small patchs， sent image patchs into network for training rather than whole images
> > 
> > 
> > I followed your configuration file. I used the label file you gave, all the data sets of train and test to train, and the average accuracy is 2-3 points lower than the one given in your article. Is this normal?
> > It's weird.
Do you divide the image into patches during training and testing?

**Comment by MingboHong** [comment]
> > > > > Hello, I use the erase_with_uncertain_dataset dataset in Tiny Person and the test results in your paper are different, which part of the dataset are you using?
> > > > 
> > > > 
> > > > emm， i guess you need to cut the image into small patchs， sent image patchs into network for training rather than whole images
> > > 
> > > 
> > > I followed your configuration file. I used the label file you gave, all the data sets of train and test to train, and the average accuracy is 2-3 points lower than the one given in your article. Is this normal?
> > > It's weird.
> 
> Do you divide the image into patches during training and testing?

yes, both phase did it.

**Comment by guyuehuqaq** [comment]
> 



> > > > > > Hello, I use the erase_with_uncertain_dataset dataset in Tiny Person and the test results in your paper are different, which part of the dataset are you using?
> > > > > 
> > > > > 
> > > > > emm， i guess you need to cut the image into small patchs， sent image patchs into network for training rather than whole images
> > > > 
> > > > 
> > > > I followed your configuration file. I used the label file you gave, all the data sets of train and test to train, and the average accuracy is 2-3 points lower than the one given in your article. Is this normal?
> > > > It's weird.
> > 
> > 
> > Do you divide the image into patches during training and testing?
> 
> yes, both phase did it.

Oh,I just tried LoadSubImageFromFile for training and verification, changed the test to LoadImageFromFile, and then used the result.pkll obtained from the trained model to test, and the average precision of the results is close to yours.

**Comment by MingboHong** [comment]
> > 
> 
> > > > > > > Hello, I use the erase_with_uncertain_dataset dataset in Tiny Person and the test results in your paper are different, which part of the dataset are you using?
> > > > > > 
> > > > > > 
> > > > > > emm， i guess you need to cut the image into small patchs， sent image patchs into network for training rather than whole images
> > > > > 
> > > > > 
> > > > > I followed your configuration file. I used the label file you gave, all the data sets of train and test to train, and the average accuracy is 2-3 points lower than the one given in your article. Is this normal?
> > > > > It's weird.
> > > 
> > > 
> > > Do you divide the image into patches during training and testing?
> > 
> > 
> > yes, both phase did it.
> 
> Oh,I just tried LoadSubImageFromFile for training and verification, changed the test to LoadImageFromFile, and then used the result.pkll obtained from the trained model to test, and the average precision of the results is close to yours.

Nice！bro

**Comment by guyuehuqaq** [comment]
> 



> > > 
> > 
> > 
> > > > > > > > Hello, I use the erase_with_uncertain_dataset dataset in Tiny Person and the test results in your paper are different, which part of the dataset are you using?
> > > > > > > 
> > > > > > > 
> > > > > > > emm， i guess you need to cut the image into small patchs， sent image patchs into network for training rather than whole images
> > > > > > 
> > > > > > 
> > > > > > I followed your configuration file. I used the label file you gave, all the data sets of train and test to train, and the average accuracy is 2-3 points lower than the one given in your article. Is this normal?
> > > > > > It's weird.
> > > > 
> > > > 
> > > > Do you divide the image into patches during training and testing?
> > > 
> > > 
> > > yes, both phase did it.
> > 
> > 
> > Oh,I just tried LoadSubImageFromFile for training and verification, changed the test to LoadImageFromFile, and then used the result.pkll obtained from the trained model to test, and the average precision of the results is close to yours.
> 
> Nice！bro
Thanks for your reply！
