### ISSUE TITLE
how to train

### ISSUE THREAD

**Issue by qitiandasheng11** [MingboHong/SSPNet-Scale-Selection-Pyramid-Network-for-Tiny-Person-Detection-from-UAV-Images#3]
i don not find a file named train,or relevant file

**Comment by MingboHong** [comment]
> i don not find a file named train,or relevant file

Hi， sorry for being late， we have released the detailed code, you can use "./dist_train.sh ../config/sspnet/faster_rcnn_r50_sspnet_1x_coco.py 2" to train sspnet.
