### ISSUE TITLE
Plz, help!

### ISSUE THREAD

**Issue by caiyaya** [MingboHong/SSPNet-Scale-Selection-Pyramid-Network-for-Tiny-Person-Detection-from-UAV-Images#4]
Hi, Could you give me some help? PLZ!!
Tiny_person dataset seems not be straight used in your project.
Could you please afford custom dataset? PlZ
Your help is important for me!!!!

**Comment by MingboHong** [comment]
> Hi, Could you give me some help? PLZ!! Tiny_person dataset seems not be straight used in your project. Could you please afford custom dataset? PlZ Your help is important for me!!!!

Hi, you can download the label file as follows:
Google Drive:https://drive.google.com/file/d/1KNACRARakvBYUuYcMUTgrfE2II_balZx/view?usp=sharing
Baidu Drive: https://pan.baidu.com/s/1-EE-libZHlwswcmYnJtVkg passwd:x433

**Comment by PrymceQ** [comment]
> > Hi, Could you give me some help? PLZ!! Tiny_person dataset seems not be straight used in your project. Could you please afford custom dataset? PlZ Your help is important for me!!!!
> 
> Hi, you can download the label file as follows: Google Drive:https://drive.google.com/file/d/1KNACRARakvBYUuYcMUTgrfE2II_balZx/view?usp=sharing Baidu Drive: https://pan.baidu.com/s/1-EE-libZHlwswcmYnJtVkg passwd:x433

Hi! This data set seems wrong,  this dataset has "no_label_images" file, and the total number of training set pictures 1174
