### ISSUE TITLE
Could you release the config file and the command you use to train TinyPerson?

### ISSUE THREAD

**Issue by JustWeZero** [MingboHong/SSPNet-Scale-Selection-Pyramid-Network-for-Tiny-Person-Detection-from-UAV-Images#5]
Thank you for your work!I want to reproduce your experiment result.

**Comment by MingboHong** [comment]
> Thank you for your work!I want to reproduce your experiment result.

Hi, we have provided a detailed code for training, now you can find them in this repo.
