### ISSUE TITLE
How many gpus are used for training

### ISSUE THREAD

**Issue by haotianll** [MingboHong/SSPNet-Scale-Selection-Pyramid-Network-for-Tiny-Person-Detection-from-UAV-Images#6]
Could you please release the experiment setup and the processed dataset? Thank you very much!

**Comment by MingboHong** [comment]
> Could you please release the experiment setup and the processed dataset? Thank you very much!
We use 2 NVIDIA RTX 2080Ti in training phase. More detailed  can be referred to this repo (we have released a full version code).

**Comment by haotianll** [comment]
Thank you so much for your reply !
