### ISSUE TITLE
La loss  "WNS"

### ISSUE THREAD

**Issue by shenxiangkei** [MingboHong/SSPNet-Scale-Selection-Pyramid-Network-for-Tiny-Person-Detection-from-UAV-Images#7]
Thank you very much for sharing your code. I want to ask a few questions. Which part of the code does "WNS" reflect? Where is La's loss? thanks

**Comment by MingboHong** [comment]
> Thank you very much for sharing your code. I want to ask a few questions. Which part of the code does "WNS" reflect? Where is La's loss? thanks

WNS can be referred to mmdet/core/bbox/samplers/ic_neg_sampler.py
La loss can be referred to mmdet/models/module/heatmap.py

**Comment by a-drop-in-the-ocean456** [comment]
> > Thank you very much for sharing your code. I want to ask a few questions. Which part of the code does "WNS" reflect? Where is La's loss? thanks
> 
> WNS can be referred to mmdet/core/bbox/samplers/ic_neg_sampler.py La loss can be referred to mmdet/models/module/heatmap.py

hello,i want to know where use the la loss ,i did not find it,thank you.
