### ISSUE TITLE
About the performance of the pretrained model

### ISSUE THREAD

**Issue by haotianll** [MingboHong/SSPNet-Scale-Selection-Pyramid-Network-for-Tiny-Person-Detection-from-UAV-Images#8]
I download the pretrained weights of "faster_rcnn_r50_sspnet" and get the following results:
```
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=200 ] = 0.6227
 Average Precision  (AP) @[ IoU=0.50      | area=  tiny | maxDets=200 ] = 0.5835
 Average Precision  (AP) @[ IoU=0.50      | area= tiny1 | maxDets=200 ] = 0.4437
 Average Precision  (AP) @[ IoU=0.50      | area= tiny2 | maxDets=200 ] = 0.6191
 Average Precision  (AP) @[ IoU=0.50      | area= tiny3 | maxDets=200 ] = 0.6693
 Average Precision  (AP) @[ IoU=0.50      | area= small | maxDets=200 ] = 0.7189
 Average Precision  (AP) @[ IoU=0.50      | area=reasonable | maxDets=200 ] = 0.7330
```
I also try to change the maxDets to 1000 and the results is:
```
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=1000 ] = 0.6251
 Average Precision  (AP) @[ IoU=0.50      | area=  tiny | maxDets=1000 ] = 0.5858
 Average Precision  (AP) @[ IoU=0.50      | area= tiny1 | maxDets=1000 ] = 0.4492
 Average Precision  (AP) @[ IoU=0.50      | area= tiny2 | maxDets=1000 ] = 0.6222
 Average Precision  (AP) @[ IoU=0.50      | area= tiny3 | maxDets=1000 ] = 0.6719
 Average Precision  (AP) @[ IoU=0.50      | area= small | maxDets=1000 ] = 0.7188
 Average Precision  (AP) @[ IoU=0.50      | area=reasonable | maxDets=1000 ] = 0.7331
```

My test command is:
```
tools/dist_test.sh configs/sspnet/faster_rcnn_r50_sspnet_1x_coco.py epoch_10.pth 2 --eval bbox 
```

So, how can I get the performance AP50 60.87 in README.md? Does the AP50 stand for AP50_tiny? Thanks!

**Comment by MingboHong** [comment]
It looks a little strange，my test performance is normal. Can u provide your envs?

**Comment by haotianliu001** [comment]
I use python 3.7 and cuda 10.2 for test. Here is some packages in pip list:
```
mmdet                  2.19.0    /root/userfolder/SSPNet
mmcv-full              1.3.18
torch                  1.10.0
```

Did you use the same config as your code [here](https://github.com/MingboHong/SSPNet/blob/master/configs/sspnet/faster_rcnn_r50_sspnet_1x_coco.py)? It uses "LoadSubImageFromFile" [here](https://github.com/MingboHong/SSPNet/blob/master/configs/_base_/datasets/coco_detection.py#L73-L74) during test.

**Comment by haotianliu001** [comment]
I use the function merge_evaluate() [here](https://github.com/MingboHong/SSPNet/blob/master/mmdet/datasets/coco.py#L467-L475) for test and I can get the correct result now. Thank you for your reply!

**Comment by freshn** [comment]
Same as @haotianliu001.

**Comment by guyuehuqaq** [comment]
> It looks a little strange，my test performance is normal. Can u provide your envs?

Hello, I use the erase_with_uncertain_dataset dataset in Tiny Person and the test results in your paper are different, which part of the dataset are you using?

**Comment by BiBiKo219** [comment]
> It looks a little strange，my test performance is normal. Can u provide your envs?

Hi, I also got the strange result. Please indicate which part of the dataset you are using. Thanks!
