### ISSUE TITLE
Why the performance is not high as the reported one in the first tiny object detection challenge?

### ISSUE THREAD

**Issue by freshn** [MingboHong/SSPNet-Scale-Selection-Pyramid-Network-for-Tiny-Person-Detection-from-UAV-Images#9]
@MingboHong  Hello. I find you and your group did a brilliant job in the first tiny object detection challenge. I am wondering why the performance you got in that competition seems higher a lot than SSPNet.

**Comment by MingboHong** [comment]
> @MingboHong Hello. I find you and your group did a brilliant job in the first tiny object detection challenge. I am wondering why the performance you got in that competition seems higher a lot than SSPNet.

We used the model ensembling strategy (weighted box fusion) in the 1st tod challenge to get more performance gains. Furthermore,  HRNet is also employed in challenge, which outperforms ResNet for tiny object detection.
